"""create deadlines table

Revision ID: 44693d36b53a
Revises: 762943d35c93
Create Date: 2026-05-15 09:03:24.965540
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '44693d36b53a'
down_revision: Union[str, None] = '762943d35c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
